=== springtg/popshop/lightPortal/WebContent/WEB-INF/portlet-config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="allowJS">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="autoRefreshed">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="configMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="editMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="helpMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="minimized">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="maximized">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="windowSkin">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="icon">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pageRefreshed">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="path">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="periodTime">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="subTag">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tag">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="language">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="portlet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="path"/>
				<xs:element ref="title"/>
				<xs:element ref="icon"/>
				<xs:element ref="url"/>
				<xs:element ref="subTag" minOccurs="0"/>
				<xs:element ref="tag"/>
				<xs:element ref="language"/>
				<xs:element ref="refreshMode"/>
				<xs:element ref="editMode"/>
				<xs:element ref="helpMode"/>
				<xs:element ref="configMode"/>
				<xs:element ref="minimized" minOccurs="0"/>
				<xs:element ref="maximized" minOccurs="0"/>
				<xs:element ref="windowSkin" minOccurs="0"/>
				<xs:element ref="autoRefreshed"/>
				<xs:element ref="periodTime"/>
				<xs:element ref="allowJS"/>
				<xs:element ref="pageRefreshed"/>
				<xs:element ref="showNumber" minOccurs="0"/>
				<xs:element ref="showType" minOccurs="0"/>
				<xs:element ref="windowStatus" minOccurs="0"/>
				<xs:element ref="mode" minOccurs="0"/>
				<xs:element ref="type" minOccurs="0"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="roles" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="roles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="role" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="role">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="portlets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="portlet" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="refreshMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="showNumber">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="showType">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="windowStatus">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="mode">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="url" type="xs:string"/>
	<xs:element name="value" type="xs:string"/>
</xs:schema>

=== springtg/popshop/trunk/lightPortal/WebContent/WEB-INF/portlet-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<portlets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="portlet-config.xsd">		
	<portlet>
	    <name>tvPortlet</name>
		<path>/iFramePortlet.lp</path>
		<title>portlet.title.tv</title>
		<icon>/light/images/video.png</icon>
		<url/>
		<tag>portlet.tag.title.entertainment</tag>
		<language>all</language>	
		<refreshMode>false</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<parameter>
			<name>url</name>
			<value>http://www.sopcast.cn/channel/getchlist.iframe.html</value>
		</parameter>
	</portlet>
	<portlet>
	    <name>iFramePortlet</name>
		<path>/iFramePortlet.lp</path>
		<title>portlet.title.iFrame</title>
		<icon></icon>
		<url/>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>	
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
	</portlet>
	<portlet>
	    <name>peopleDirectoryPortlet</name>
		<path>/peopleDirectoryPortlet.lp</path>
		<title>portlet.title.findMember</title>
		<icon>/light/images/friend.gif</icon>
		<url/>
		<tag>portlet.tag.title.search</tag>
		<language>all</language>
		<refreshMode>false</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<windowSkin>PortletWindow3</windowSkin>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>	
	</portlet>
	<portlet>
	    <name>globalSearchPortlet</name>
		<path>/globalSearchPortlet.lp</path>
		<title>portlet.title.search</title>
		<icon>/light/images/search.gif</icon>
		<url/>
		<tag>portlet.tag.title.search</tag>
		<language>all</language>
		<refreshMode>false</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<windowSkin>PortletWindow3</windowSkin>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>	
	</portlet>
	<portlet>
	    <name>businessPortlet</name>
		<path>/businessPortlet.lp</path>
		<title>Business</title>
		<icon>/light/images/business.gif</icon>
		<url/>
		<tag>default</tag>
		<language>all</language>
		<refreshMode>false</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>	
		<roles>
			<role>role_biz</role>
		</roles>	
	</portlet>
	<portlet>
	    <name>infoPortlet</name>
		<path>/infoPortlet.lp</path>
		<title>Information</title>
		<icon>/light/images/logoSmall.gif</icon>
		<url/>
		<tag>System</tag>
		<language>all</language>
		<refreshMode>false</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<roles>
			<role>role_admin</role>
		</roles>		
	</portlet>
	<portlet>
	    <name>addressbookPortlet</name>
		<path>/addressbookPortlet.lp</path>
		<title>portlet.title.addressbook</title>
		<icon>/light/images/addressbook.gif</icon>
		<url/>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>
		<refreshMode>false</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>	
		<type>1</type>	
	</portlet>
	<portlet>
	    <name>emailPortlet</name>
		<path>/emailPortlet.lp</path>
		<title>portlet.title.email</title>
		<icon>/light/images/popmail.gif</icon>
		<url/>
		<tag>portlet.tag.title.communication</tag>
		<language>all</language>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>		
	</portlet>
	<portlet>
	    <name>gmailPortlet</name>
		<path>/gmailPortlet.lp</path>
		<title>portlet.title.gmail</title>
		<icon>/light/images/gmail.gif</icon>
		<url/>
		<tag>portlet.tag.title.communication</tag>
		<language>all</language>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>		
	</portlet>
	<portlet>
	    <name>calendarPortlet</name>
		<path>/calendarPortlet.lp</path>
		<title>portlet.title.calendar</title>
		<icon>/light/images/calendar.gif</icon>
		<url/>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>	
		<type>1</type>				
	</portlet>
	
	<portlet>
	    <name>searchPortlet</name>
		<path>/searchPortlet.lp</path>
		<title>portlet.title.search</title>
		<icon>/light/images/search.gif</icon>
		<url/>
		<tag>portlet.tag.title.search</tag>
		<language>all</language>	
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
	</portlet>	
	<portlet>
	    <name>dictionaryPortlet</name>
		<path>/dictionaryPortlet.lp</path>
		<title>portlet.title.dictionary</title>
		<icon>/light/images/dictionary.gif</icon>
		<url/>
		<tag>portlet.tag.title.search</tag>
		<language>all</language>	
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
	</portlet>
	<portlet>
	    <name>mapPortlet</name>
		<path>/mapPortlet.lp</path>
		<title>portlet.title.map</title>
		<icon>/light/images/google.gif</icon>
		<url>http://maps.google.com/</url>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>		
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
	</portlet>
	<portlet>
	    <name>weatherPortlet</name>
		<path>/weatherPortlet.lp</path>
		<title>portlet.title.weather</title>
		<icon>/light/images/weather.gif</icon>
		<url>http://www.weather.com</url>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
	</portlet>
	<portlet>
	    <name>bookmarkPortlet</name>
		<path>/bookmarkPortlet.lp</path>
		<title>portlet.title.bookmark</title>
		<icon>/light/images/bookmark.gif</icon>
		<url/>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<type>1</type>	
	</portlet>	
	<portlet>
	    <name>todoListPortlet</name>
		<path>/todoListPortlet.lp</path>
		<title>portlet.title.todolist</title>
		<icon>/light/images/todolist.gif</icon>
		<url/>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>
		<refreshMode>false</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<type>1</type>	
	</portlet>	
	<portlet>
	    <name>feedbackPortlet</name>
		<path>/feedbackPortlet.lp</path>
		<title>portlet.title.feedback</title>
		<icon>/light/images/todolist.gif</icon>
		<url/>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>true</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<roles>
		   <role>role_admin</role>
		</roles>
	</portlet>	
	<portlet>
	    <name>deliciousPortlet</name>
		<path>/deliciousPortlet.lp</path>
		<title>portlet.title.delicious</title>
		<icon>/light/images/delicious.gif</icon>
		<url>http://del.icio.us/</url>
		<tag>portlet.tag.title.tools</tag>
		<language>all</language>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>true</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
	</portlet>
	<portlet>
	    <name>notePortlet</name>
		<path>/notePortlet.lp</path>
		<title>portlet.title.note</title>
		<icon>/light/images/note.gif</icon>
		<url/>
